camera:
  initial_exposure: 30000
  initial_gain: 1.0
  frame_width: 640
  frame_height: 480
  roi_fraction: 0.33

auto_exposure:
  low_pct: 10
  high_pct: 90
  target_cover_min: 0.1
  target_cover_max: 0.3
  max_delta: 50

smoothing:
  alpha_cx: 0.3
  alpha_roi: 0.2

morphology:
  min_area_factor: 0.5
  max_area_factor: 2.0

serial:
  baudrate: 9600
  throttle_ms: 20

camera:
  initial_exposure: 30000
  initial_gain: 1.0
  frame_width: 640
  frame_height: 480
  roi_fraction: 0.33
